# This is a config for E2B sandbox template.
# You can use template ID (3mna658ol56wt26h8zqz) or template name (xuroth_vibe-ai-nextjs_testing-0) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("xuroth_vibe-ai-nextjs_testing-0") # Sync sandbox
# sandbox = await AsyncSandbox.create("xuroth_vibe-ai-nextjs_testing-0") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('xuroth_vibe-ai-nextjs_testing-0')

team_id = "eeb46dbb-5393-4f29-9ea3-6d301c54d544"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "xuroth_vibe-ai-nextjs_testing-0"
template_id = "3mna658ol56wt26h8zqz"
